### ISSUE TITLE
Import error DLL load failed

### ISSUE THREAD

**Issue by Romain-Morichon** [MIAnalyzer/MIA#4]
Hi,
i've installed your software on a conda environment. But when try to launch it, i've got this message:

(mia_environment) C:\Users\StationAnalyse\Downloads>mianalyzer
Traceback (most recent call last):
  File "C:\Users\StationAnalyse\anaconda3\envs\mia_environment\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\StationAnalyse\anaconda3\envs\mia_environment\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\StationAnalyse\anaconda3\envs\mia_environment\Scripts\mianalyzer.exe\__main__.py", line 7, in <module>
  File "C:\Users\StationAnalyse\anaconda3\envs\mia_environment\lib\site-packages\mia\startup.py", line 27, in start
    from mia_gui import MIA_UI
  File "C:\Users\StationAnalyse\anaconda3\envs\mia_environment\lib\site-packages\mia\mia_gui.py", line 27, in <module>
    import dl.DeepLearning as DeepLearning
  File "C:\Users\StationAnalyse\anaconda3\envs\mia_environment\lib\site-packages\mia\dl\DeepLearning.py", line 21, in <module>
    import dl.training.datagenerator as datagenerator
  File "C:\Users\StationAnalyse\anaconda3\envs\mia_environment\lib\site-packages\mia\dl\training\datagenerator.py", line 16, in <module>
    import dl.utils.dl_utils as dl_utils
  File "C:\Users\StationAnalyse\anaconda3\envs\mia_environment\lib\site-packages\mia\dl\utils\dl_utils.py", line 3, in <module>
    from skimage.measure import label
  File "C:\Users\StationAnalyse\anaconda3\envs\mia_environment\lib\site-packages\skimage\measure\__init__.py", line 7, in <module>
    from ._polygon import approximate_polygon, subdivide_polygon
  File "C:\Users\StationAnalyse\anaconda3\envs\mia_environment\lib\site-packages\skimage\measure\_polygon.py", line 2, in <module>
    from scipy import signal
  File "C:\Users\StationAnalyse\anaconda3\envs\mia_environment\lib\site-packages\scipy\signal\__init__.py", line 302, in <module>
    from .filter_design import *
  File "C:\Users\StationAnalyse\anaconda3\envs\mia_environment\lib\site-packages\scipy\signal\filter_design.py", line 16, in <module>
    from scipy import special, optimize, fft as sp_fft
  File "C:\Users\StationAnalyse\anaconda3\envs\mia_environment\lib\site-packages\scipy\optimize\__init__.py", line 400, in <module>
    from .optimize import *
  File "C:\Users\StationAnalyse\anaconda3\envs\mia_environment\lib\site-packages\scipy\optimize\optimize.py", line 36, in <module>
    from ._numdiff import approx_derivative
  File "C:\Users\StationAnalyse\anaconda3\envs\mia_environment\lib\site-packages\scipy\optimize\_numdiff.py", line 6, in <module>
    from scipy.sparse.linalg import LinearOperator
  File "C:\Users\StationAnalyse\anaconda3\envs\mia_environment\lib\site-packages\scipy\sparse\linalg\__init__.py", line 114, in <module>
    from .eigen import *
  File "C:\Users\StationAnalyse\anaconda3\envs\mia_environment\lib\site-packages\scipy\sparse\linalg\eigen\__init__.py", line 9, in <module>
    from .arpack import *
  File "C:\Users\StationAnalyse\anaconda3\envs\mia_environment\lib\site-packages\scipy\sparse\linalg\eigen\arpack\__init__.py", line 20, in <module>
    from .arpack import *
  File "C:\Users\StationAnalyse\anaconda3\envs\mia_environment\lib\site-packages\scipy\sparse\linalg\eigen\arpack\arpack.py", line 42, in <module>
    from . import _arpack
ImportError: DLL load failed: La procédure spécifiée est introuvable.

i've you got a solution to this issue?

Regards

Romain

**Comment by nkoerb** [comment]
see here: https://forum.image.sc/t/launching-error-mia-with-dll-load-failed/84304
